<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SearchRoom.aspx.cs" Inherits="WebHotelSystemApp.SearchRoom" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Wyszukaj pokoj</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:azure">
    <div>
        <br /><br />
    </div>
    <form id="form1" runat="server">
        <div>
    <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>person num</th>
        <th>floor</th>
        <th>price</th>
        <th>status</th>
      </tr>
    </thead>
    <tbody>
    <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
            
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        <tr>
        <td>
                <%
                    Response.Write(returnId().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPersonNum().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnFloor().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnPrice().ToString());
                %> 
        </td>
        <td>
                <%
                    Response.Write(returnSatus());
                %> 
        </td>
    </tr>
        
    </tbody>
  </table>
        </div>
        <div style="height: 261px">
            <div style="text-align:center; overflow: auto; margin-left:auto; margin-right:auto;display:block">
            <br />
            <asp:Label ID="Label1" runat="server" Text="IdPokoju"></asp:Label>
                <br />
                <asp:DropDownList ID="DropDownList1" runat="server" Height="28px" Width="124px">
                    <asp:ListItem>1</asp:ListItem>
                    <asp:ListItem>2</asp:ListItem>
                    <asp:ListItem>3</asp:ListItem>
                    <asp:ListItem>4</asp:ListItem>
                    <asp:ListItem>5</asp:ListItem>
                    <asp:ListItem>6</asp:ListItem>
                    <asp:ListItem>7</asp:ListItem>
                    <asp:ListItem>8</asp:ListItem>
                    <asp:ListItem>9</asp:ListItem>
                    <asp:ListItem>10</asp:ListItem>
                    <asp:ListItem>11</asp:ListItem>
                    <asp:ListItem>12</asp:ListItem>
                    <asp:ListItem>13</asp:ListItem>
                    <asp:ListItem>14</asp:ListItem>
                    <asp:ListItem>15</asp:ListItem>
                    <asp:ListItem>16</asp:ListItem>
                    <asp:ListItem>17</asp:ListItem>
                    <asp:ListItem>18</asp:ListItem>
                    <asp:ListItem>19</asp:ListItem>
                    <asp:ListItem>20</asp:ListItem>
                </asp:DropDownList>
            <br /><br />
            <asp:Label ID="Label2" runat="server" Text="Od:"></asp:Label>
                <br />
                <div style="width:200px;margin-left:auto;margin-right:auto">
            <asp:TextBox ID="Calendar2" runat="server" Width="171px" TextMode="Date"></asp:TextBox>
                    </div>
            <br /><br />
            <asp:Label ID="Label3" runat="server" Text="Do:"></asp:Label>
                <br />
                <div style="width:200px;margin-left:auto;margin-right:auto">
                <asp:TextBox ID="Calendar1" runat="server" Width="171px" TextMode="Date"></asp:TextBox>
                    </div>
                <br /><br />
                <asp:Label ID="Label4" runat="server" Text="Potwierdz login"></asp:Label>
            <br/>
            <asp:TextBox ID="TextBox1" runat="server" Width="171px"></asp:TextBox>
            <br/>
            <asp:Label ID="Label5" runat="server" Text="Potwierdz hasło"></asp:Label>
            <br/>
            <asp:TextBox ID="TextBox2" runat="server" TextMode="Password" Width="171px"></asp:TextBox>
            
            <br /><br />
            <asp:Button ID="Button1" runat="server" Text="Zarezerwuj" OnClick="Button1_Click" />
            </div>
        </div>
    </form>
    <div>
        <br /><br /><br /><br />
    </div>
    </body>
</html>
